version: '3'

services:
  app:
    container_name: next-app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - /code/node_modules
    env_file:
      - .env.dev
